# Generated by Django 5.0.4 on 2024-04-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trade_trader_trader_edad_trader_intercambios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='categoria',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trade',
            name='condicion',
            field=models.CharField(choices=[('MALA', 'MALA'), ('BUENA', 'BUENA'), ('COMO NUEVO', 'COMO NUEVO'), ('NUEVO', 'NUEVO')], default='BUENA', max_length=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trade',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trade',
            name='intercambio_preferente',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='titulo',
            field=models.CharField(default='Trade Producto', max_length=100),
        ),
    ]
