# Generated by Django 5.0.4 on 2024-04-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trade_categoria_trade_condicion_trade_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='categoria',
            field=models.CharField(choices=[('TALENTO/CONOCIMIENTO', 'TALENTO/CONOCIMIENTO'), ('OBJETO MATERIAL', 'OBJETO MATERIAL'), ('SERVICIO', 'SERVICIO')], default='', max_length=200),
        ),
    ]
